include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true

    # Documentation
    public_member_api_docs: false

    # Formatting
    lines_longer_than_80_chars: false

    # Best practices
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
